CREATE TABLE users (
                    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    "email" varchar(64) unique ,
                    "name" varchar(64) ,
                    "password" varchar(64) ,
                    "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
                    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE drug_categories (
                    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    "name" varchar(256) ,
                    "description" text, 
                    "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
                    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE drugs (
                    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "drug_category_id"   bigint REFERENCES drug_categories(id),  
                    "name" varchar(256) ,
                    "image_url" text NOT NULL, 
                    "description" text NOT NULL, 
                    "side_effects" text NOT NULL, 
                    "warnings" text NOT NULL, 
                    "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
                    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE user_drugs (
                    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    "user_id"   bigint REFERENCES users(id), 
                    "drug_id"   bigint REFERENCES drugs(id), 
                    "is_fasting" boolean NOT NULL DEFAULT FALSE,
                    "status" varchar(16) DEFAULT 'ACTIVE',
                    "dosage_frequency" int,
                    "start_date" TIMESTAMPTZ,
                    "end_date" TIMESTAMPTZ,
                    "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
                    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

