swagger: "2.0"
info:
  title: Drugs APP Service
  description: API Documentaion for Drugs APP
  version: 1.0.0 
schemes:
  - "http"
  - "https"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /login:
    post:
      tags:
        - "auth"
      operationId: login
      summary: login
      parameters:
        - in: body
          name: loginRequest
          schema:
            $ref: "#/definitions/LoginRequest"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successful
          schema:
            $ref: "#/definitions/LoginResponse"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

definitions:

  LoginRequest:
    type: object
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
    required: ["email","password"]

  LoginResponse:
    type: object
    properties:
      token:
        type: string
      user_id:
        type: integer
        format: uint64 
      email:
        type: string
      name:
        type: string

  SignupRequest:
    type: object
    properties:
      email:
        type: string
        format: email
      name:
        type: string
      password:
        type: string
        format: password
      password_confirm:
        type: string
        format: password
    required: ["email","password","password_confirm","name"]







  PostTableRequest:
      type: object
      description: Parameters for table request
      properties:
        page:
          type: integer
          format: int64
          default: 1
        pageSize:
          type: integer
          format: int64
          default: 10
        sort:
          type: object
          additionalProperties:
            type: string
            enum: [asc, desc]
          x-nullable: true
        search:
          type: string
          x-nullable: true
        filters:
          type: array
          items:
            $ref: "#/definitions/Filter"
          x-nullable: true
  Filter:
      type: object
      description: Single filter object for tables
      properties:
        key:
          type: string
        op:
          type: string
          enum: [eq, ne, ct, in, notin, sw, ew, like, gt, ge, lt, le]
        value: {}
      required:
        - key
        - op
        - value






  DrugsTableResponse:
    type: object
    properties:
      records:
        type: array
        items:
          $ref: "#/definitions/DrugsResponse"
      total_records:
        type: integer
        format: uint64

  DrugsResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint64
      name:
        type: string
      image_url:
        type: string
      description:
        type: string
      side_effects:
        type: string
      warnings:
        type: string
      drug_category_id:
        type: integer
        format: uint64
      drug_category_name:
        type: string
      drug_category_description:
        type: string





  DrugCategoriesTableResponse:
    type: object
    properties:
      records:
        type: array
        items:
          $ref: "#/definitions/DrugCategoriesResponse"
      total_records:
        type: integer
        format: uint64

  DrugCategoriesResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint64
      name:
        type: string
      description:
        type: string
     




  AddUserDrugsRequest:
    type: object
    properties:
      drug_id:
        type: integer
        format: uint64
      is_fasting:
        type: boolean
      dosage_frequency:
        type: integer
        format: uint64
        minimum: 0
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
        x-nullable: true
      status:
        type: string
        enum: ["ACTIVE", "PAUSED"]
        x-nullable: true
    required: ["drug_id","is_fasting","dosage_frequency","start_date"]

  UserDrugsTableResponse:
    type: object
    properties:
      records:
        type: array
        items:
          $ref: "#/definitions/UserDrugResponse"
      total_records:
        type: integer
        format: uint64

  UserDrugResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint64
      drug_id:
        type: integer
        format: uint64
      name:
        type: string
      image_url:
        type: string
      description:
        type: string
      is_fasting:
        type: boolean
      dosage_frequency:
        type: integer
        format: uint64
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      status:
        type: string
      side_effects:
        type: string
      warnings:
        type: string
      drug_category_id:
        type: integer
        format: uint64
      drug_category_name:
        type: string
      drug_category_description:
        type: string
   
    